### ISSUE TITLE
Add Node ED25519 native support

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/ed25519-verification-key-2020#2]
1. if this module is being used in node use node's crypto lib
2. ensure usage does not break 2020 spec
3. Branch from this PR: https://github.com/digitalbazaar/ed25519-verification-key-2020/pull/1
4. https://nodejs.org/api/crypto.html#crypto_crypto_createprivatekey_key
5. make node-forge a webpack alias only included in node and not the browser
6. use the asn1 code from previous verification keys here

What we use now:

[`@stablelib/ed25519`](https://github.com/StableLib/stablelib/tree/master/packages/ed25519)
[`@stablelib/random`](https://github.com/StableLib/stablelib/tree/master/packages/random)

**Comment by mattcollier** [comment]
I recently updated crypto-bench to include Node.cryto ed25519 verify: https://github.com/digitalbazaar/crypto-bench#nodejs-14151-amd-ryzen-5-3600-with-sha_ni-capability

**Comment by dmitrizagidulin** [comment]
Implemented in latest PR, closing.
